### ISSUE TITLE
Let minimum-stability be stable

### ISSUE THREAD

**Issue by peter279k** [laravie/webhook#1]
In `composer.json`, defining the `minimum-stability` to be `stable` means the package dependencies will be installed as unstable version during `composer install` command work.

To avoid installing unstable version and some dependency surprises, I think we can consider removing this setting because the default `minimum-stability` is `stable`.

The detailed description is available [here](https://getcomposer.org/doc/04-schema.md#minimum-stability).

**Comment by crynobone** [comment]
No, the current structure is fine for **library** because we want to tests against lowest, stable, and latest unstable commit. For your **project**'s `composer.json` where this option would be useful.
